# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_date', models.DateTimeField(auto_now=True)),
                ('giruda', models.CharField(choices=[('S', 'Spade'), ('D', 'Diamond'), ('C', 'Club'), ('H', 'Heart'), ('N', 'No Giruda')], max_length=1)),
                ('bid', models.SmallIntegerField()),
                ('score', models.SmallIntegerField()),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_histories', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='game_histories', to=settings.AUTH_USER_MODEL)),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
