# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('is_private', models.BooleanField()),
                ('password', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='avatar'),
        ),
    ]
