# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171113_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(max_length=120),
        ),
    ]
