# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171114_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player_number',
            field=models.SmallIntegerField(default=0),
        ),
    ]
