# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_player_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
