# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 18:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20171216_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='lose_players',
            field=models.ManyToManyField(related_name='lose_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='win_players',
            field=models.ManyToManyField(related_name='win_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
